name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.13.0
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - notebook
  - matplotlib
  - numpy
  - vpython
  - pandas
  - metakernel
  - pip:
    - calysto_scheme
    - metakernel
    - numpy
    - calysto
    - yasi